### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by lukekrikorian** [BlazeProgramming/Tucker#14]
I think this is a chat bot of some sort, just from looking through the source. What exactly is it? The README left something to be desired 😄

**Comment by 1kq2lo40lozpmb63** [comment]
It's a discord bot for the Khan Academy server. It basically performs useful tasks and has a database of users.

**Comment by CosignCosine** [comment]
I'm going to fix the readme eventually ;)

**Comment by kingcodefish** [comment]
Please don't use "Issues" for discussion.

**Comment by lukekrikorian** [comment]
kingcodefish, how would you suggest I discuss this?
