### ISSUE TITLE
Modular Commands

### ISSUE THREAD

**Issue by kingcodefish** [BlazeProgramming/Tucker#6]
Right now your code is very static in nature. A modular design would give it a better feel IMO. I think it would increase productivity, make the code more self-documented, and make debugging easier because everything is "extended" from the base code.

Basically, my idea was to change stuff like this:

``` js
// Gargantuan 'switch' statement here...
case "!promote": {
    // .....
}
```

To something more like this:

``` js
commands.push(new Command("promote", {
    // The innards of said command will bid all our servants to step up for promotion!
}));
```

This way we can control the base `Command` class and distribute certain capabilities throughout all the commands. This will make debugging easier because then we can find if the issue is occurring in all commands or a single one and edit them with ease. (Oh and **cough** make sure to use ES6 👍)

What do you think of this? It will obviously require a bit of work in restructuring, but I believe it would make using the code (`<-- gerund being used as object of a preposition....I'm a nerd.`) a lot less hectic.

**Comment by CosignCosine** [comment]
I agree heavily! However, the Cloud9 node system (that you know) that I'm using to run the infinite sh command that the bot is run off is in ES5, and I don't know when it will be upgraded. I will definitely add that system above when I have time though, but sadly I don't have ES6 yet :(

**Comment by kingcodefish** [comment]
Is it possible to use the Babylon engine to get around that?

**Comment by CosignCosine** [comment]
Actually, the system you propose might lower the code line count by over 150 lines... that would be great. 

I'm researching the Babylon engine right now.

**Comment by kingcodefish** [comment]
Sorry, I meant to say Babel, not Babylon lol.

**Comment by CosignCosine** [comment]
Lol! I'll research that instead.

**Comment by 1kq2lo40lozpmb63** [comment]
Why do you need ES6 to put this into effect?

**Comment by 1kq2lo40lozpmb63** [comment]
``` javascript
commands.push(new Command("promote", function () {
    // codes lol
}));
```

**Comment by kingcodefish** [comment]
You don't, but ES6 classes would be nice. That's what I was referencing.

**Comment by 1kq2lo40lozpmb63** [comment]
Well, why not create a simple constructor function? Or just have an object of functions:

``` javascript
{
"!help": function (args) { /* ... */ },
"!eval": function (args) { /* ... */ },
// ...
}
```

**Comment by kingcodefish** [comment]
I was also thinking about that. It's entirely up to Blaze. I just really am not fond of the static nature and `switch` statement that is currently found managing all the command memory storage. 😕

**Comment by 1kq2lo40lozpmb63** [comment]
True. I believe it's best practice to use a dictionary as shown above; the structure is very useful and not messy.

On-topic, I recently told Blaze how I was seriously impressed at how he got the code **so** messy yet work **mostly** 24/7.

**Comment by CosignCosine** [comment]
_randomly appears_
Thank you
_disappears back into the void_

**Comment by kingcodefish** [comment]
As per the dictionary, my thoughts too.

Yes, it's quite impressive.

**Comment by kingcodefish** [comment]
Actually, I just realized why I didn't want dictionary key-sort approach @raumaankidwai. The reason for this being that I wanted to make debugging easier like I mentioned in the OP post. Most of the commands share a base setup and base functionalities, so I believe an extendable class parent would be more appropriate in this situation. And as you should know, @BlazeProgramming likes to create bugs in the least likely of situations..... 😝

**Comment by 1kq2lo40lozpmb63** [comment]
True, but with a dictionary, you can look up the command and perform the same operations on all commands, making it close to a class but much more intuitive.

**Comment by kingcodefish** [comment]
Well, it's only _if_ the setup is actually set up properly.

**Comment by 1kq2lo40lozpmb63** [comment]
Which, given @BlazeProgramming , is never going to happen. I see your point now.

No offense Blaze.

**Comment by kingcodefish** [comment]
I am pending the removal of my rights to this repository now................. ☢️

**Comment by 1kq2lo40lozpmb63** [comment]
True. I fixed as many spelling errors as I could (it was really hard without regex!) and I hope to not need to look at this code again until it is properly fixed.

**Comment by kingcodefish** [comment]
I actually just want to take the bot for myself for a little bit and restructure the whole thing.

**Comment by 1kq2lo40lozpmb63** [comment]
Not a bad idea. Then you might as well put a huge pull request in a couple ~~weeks~~ months.

**Comment by kingcodefish** [comment]
It would probably take only a few hours worth of work. I just don't have the time to do so ATM. Maybe, just maybe, later today I'll get around to it.

**Comment by CosignCosine** [comment]
To be honest, I have absolutely 0 idea of how to do that, so I most probably will not implement it right now unless I had a full team of developers. I'm going to try to work out a system on a test bot during math and band on Monday, and perhaps I could start re-writing the code over the week. I just re-wrote the whole thing from an absolutely horrible if/else system, though... xD

**Comment by kingcodefish** [comment]
Wait, you're going to do this during band practice and math class? Shame on you.....

And TBH, this system is quite easy to implement. I can literally do it in a few hours and have the whole thing redesigned for the better.

**Comment by CosignCosine** [comment]
Yes, because my math teacher never actually teaches anything and I play bells in band (and right now we're doing football pep band. So it's basically like having three study halls, including my actual study hall).
