### ISSUE TITLE
Need to re-integrate RK's edits with the new version of the bot

### ISSUE THREAD

**Issue by CosignCosine** [BlazeProgramming/Tucker#9]
I need to finish re-editing the things RK removed, so I'm just reminding myself here.

**Comment by CosignCosine** [comment]
Finished.

**Comment by kingcodefish** [comment]
@BlazeProgramming If you fixed this issue in a commit, please post the commit ID so we can view your changes at any time.

**Comment by CosignCosine** [comment]
The issue is #5 and the commit is `8d60bbd`.

**Comment by kingcodefish** [comment]
That didn't post the commit link. I believe you have to post this: #8d60bbd

**Comment by kingcodefish** [comment]
8d60bbda88d74781f32985caa5df7d273b27ca4b
